### ISSUE TITLE
Full code release

### ISSUE THREAD

**Issue by WandererGuy** [CSSLabNKU/Random-Forest-Password-Guessing#1]
Great to see this paper finally have code. Can I ask when the code will be released. Btw, thank you guys so much for publish Targuess I code. <3

**Comment by CSSLabNKU** [comment]
We're delighted to know that our open-source code has been of help to you. Our Random Forest Guessing code is expected to be released by the end of this month or in the early days of next month. Thank you for your patience.

**Comment by WandererGuy** [comment]
Ok, got it. Thank you guys.
